name: CI

concurrency: ci-${{ github.ref }}

on:
    push:
        branches: [develop]
        paths:
            - "**/*.go"
            - go.mod
            - go.sum
            - .go-version
    workflow_dispatch:

jobs:
    tests:
        name: ${{ matrix.name }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    - {
                          name: Linux,
                          os: ubuntu-latest,
                      }
        steps:
            - uses: actions/checkout@v6
            - name: Set up Go
              uses: actions/setup-go@v7
              with:
                go-version-file: go.mod
            - name: Build
              run: go build -v ./...
            - name: Test
              run: go test -v ./...

    #    docs:
    #        needs: [tests]
    #        runs-on: ubuntu-latest
    #        concurrency: docs
    #        steps:
    #            - uses: actions/checkout@v6
    #            - uses: actions/setup-python@v5
    #              with:
    #                  python-version: "3.11"
    #            - name: install-deps
    #              run: pip install -r requirements/docs.txt
    #            - name: make-docs
    #              run: cd docs && make html
    #            - name: publish-docs
    #              uses: peaceiris/actions-gh-pages@v3
    #              with:
    #                  github_token: ${{ secrets.GITHUB_TOKEN }}
    #                  publish_dir: ./docs/_build/html

    tag:
        needs: [tests]
        runs-on: ubuntu-latest
        permissions:
            contents: write
        concurrency: publish
        steps:
            - uses: actions/checkout@v6
              with:
                  fetch-depth: 0
            - name: Bump version and push tag
              uses: anothrNick/github-tag-action@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  WITH_V: true
                  DEFAULT_BUMP: patch

    notify:
        needs: [tag]
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - repo: api-core
                    - repo: catalog-api
                    - repo: catalog-data
                    - repo: catalog-data-processor
                    - repo: catalog-objects
                    - repo: catalog-web
                    - repo: client
                    - repo: data-api
                    - repo: data-objects
                    - repo: db
                    - repo: initiative-api
                    - repo: initiative-data
                    - repo: initiative-objects
                    - repo: initiative-web
                    - repo: kv-api
                    - repo: kv-data
                    - repo: kv-expression-processor
                    - repo: kv-key-processor
                    - repo: kv-objects
                    - repo: kv-value-calculator
                    - repo: kv-web
                    - repo: game-room-api
                    - repo: library-data
                    - repo: game-room-objects
                    - repo: game-room-web
                    - repo: main-web
                    - repo: model-core
                    - repo: shared-web
                    - repo: web-core
        steps:
            - uses: juztcode/repo-ditpatch-action@v1
              continue-on-error: true
              with:
                event-type: game-room-objects-published
                token: ${{ secrets.REPO_ACCESS_TOKEN }}
                repository: sweetrpg/${{ matrix.repo }}
